[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run migrate && npm start"
restartPolicyType = "always"
healthcheckPath = "/health"
healthcheckTimeout = 60

[environments.production]
variables = {}

[environments.staging]
variables = {}
